# gvbench sequence
data:
  name: weather
  image_dir: dataset/images
  pairs_info: dataset/gt/weather.txt
  image_width: 512
  image_height: 288

# matchers you want to test
matcher: [master, superpoint-lg, disk-lg, roma, sift-nn, sift-lg, duster, xfeat]